[package]
name = "kclvm-driver"
version = "0.4.5"
edition = "2021"

# # See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kclvm-config ={ path = "../config", version = "0.4.5"}
kclvm-runtime ={ path = "../runtime", version = "0.4.5"}
kclvm-utils ={ path = "../utils", version = "0.4.5"}
kclvm-parser ={ path = "../parser", version = "0.4.5"}
kclvm-ast ={ path = "../ast", version = "0.4.5"}
